services:
  sushi_app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres_db
    networks:
      - sushi_app_network
    environment:
      - POSTGRES_URL=postgres_db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=sushi_app_db
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
  postgres_db:
    image: postgres:16.3-alpine
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sushi_app_db
    networks:
      - sushi_app_network

networks:
  sushi_app_network:
    driver: bridge
    name: sushi_app_network
